apiVersion: v1
kind: Service
metadata:
  name: fitcenter-backend-service

spec:
  selector:
    app: fitcenter-backend

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: ClusterIP