apiVersion: v1
kind: Service
metadata:
  name: fitcenter-frontend-service
spec:
  selector:
    app: fitcenter-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP